[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "nextgen_plugins"
authors = [{ name = "Aquaveo LLC", email = "gromero@aquaveo.com" }]
license = { file = "LICENSE" }
readme = "README.md"
classifiers = ["License :: OSI Approved :: MIT License"]
version = "0.0.2"
description = "Module Federation MFE subproject for NRDS table/plot/map/markdown panels consumed by tethysdash at runtime"
requires-python = ">=3.6"
dependencies = []

[project.urls]
Homepage = "https://github.com/FIRO-Tethys/nextgen_plugins"
Issues = "https://github.com/FIRO-Tethys/nextgen_plugins/issues"

[tool.setuptools]
include-package-data = true
zip-safe = false

[tool.setuptools.packages.find]
include = ["*"]

[tool.setuptools.package-data]
"nextgen_plugins" = ["static/*.png", "static/*.jpg"]
